services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    image: rag-101-api:latest
    container_name: rag-101-api
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NATS_URL=nats://milvus-nats:4222
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s